[2020-06-01 16:12:53,068] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: covid_italy_daily.check_public_data_exists 2020-06-01T14:10:14.237637+00:00 [queued]>
[2020-06-01 16:12:53,072] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: covid_italy_daily.check_public_data_exists 2020-06-01T14:10:14.237637+00:00 [queued]>
[2020-06-01 16:12:53,072] {__init__.py:1353} INFO - 
--------------------------------------------------------------------------------
[2020-06-01 16:12:53,072] {__init__.py:1354} INFO - Starting attempt 2 of 2
[2020-06-01 16:12:53,072] {__init__.py:1355} INFO - 
--------------------------------------------------------------------------------
[2020-06-01 16:12:53,078] {__init__.py:1374} INFO - Executing <Task(BigQueryCheckOperator): check_public_data_exists> on 2020-06-01T14:10:14.237637+00:00
[2020-06-01 16:12:53,078] {base_task_runner.py:119} INFO - Running: ['airflow', 'run', 'covid_italy_daily', 'check_public_data_exists', '2020-06-01T14:10:14.237637+00:00', '--job_id', '43', '--raw', '-sd', 'DAGS_FOLDER/covid_italy_daily.py', '--cfg_path', '/var/folders/y6/nhshp1rd3kj1kwtclmvq1nfsrtp362/T/tmpu71di0xr']
[2020-06-01 16:12:53,793] {base_task_runner.py:101} INFO - Job 43: Subtask check_public_data_exists [2020-06-01 16:12:53,793] {__init__.py:51} INFO - Using executor SequentialExecutor
[2020-06-01 16:12:53,995] {base_task_runner.py:101} INFO - Job 43: Subtask check_public_data_exists [2020-06-01 16:12:53,994] {__init__.py:305} INFO - Filling up the DagBag from /Users/rebecca.vickery/Documents/Github/airflow_sandbox/airflow/dags/covid_italy_daily.py
[2020-06-01 16:12:54,316] {base_task_runner.py:101} INFO - Job 43: Subtask check_public_data_exists [2020-06-01 16:12:54,316] {cli.py:517} INFO - Running <TaskInstance: covid_italy_daily.check_public_data_exists 2020-06-01T14:10:14.237637+00:00 [running]> on host HX3286T2.local
[2020-06-01 16:12:54,329] {check_operator.py:80} INFO - Executing SQL check: 
                            select count(*) > 0
                            from bigquery-public-data.covid19_italy.data_by_region
                            where DATE(date) = '2020-06-01'
                        
[2020-06-01 16:12:54,768] {logging_mixin.py:95} WARNING - /Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/contrib/hooks/bigquery_hook.py:739: DeprecationWarning: Deprecated parameter `bql` used in `BigQueryBaseCursor.run_query` Use `sql` parameter instead to pass the sql to be executed. `bql` parameter is deprecated and will be removed in a future version of Airflow.
  category=DeprecationWarning)
[2020-06-01 16:12:56,097] {logging_mixin.py:95} INFO - [2020-06-01 16:12:56,097] {bigquery_hook.py:1251} INFO - Waiting for job to complete : sandbox-278915, job_OfnHAni8PchiJ-Q3XmhjNFNYfZFO
[2020-06-01 16:13:01,624] {check_operator.py:82} INFO - Record: [False]
[2020-06-01 16:13:01,628] {__init__.py:1580} ERROR - Test failed.
Query:

                            select count(*) > 0
                            from bigquery-public-data.covid19_italy.data_by_region
                            where DATE(date) = '2020-06-01'
                        
Results:
[False]
Traceback (most recent call last):
  File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/models/__init__.py", line 1441, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/operators/check_operator.py", line 87, in execute
    raise AirflowException(exceptstr.format(q=self.sql, r=records))
airflow.exceptions.AirflowException: Test failed.
Query:

                            select count(*) > 0
                            from bigquery-public-data.covid19_italy.data_by_region
                            where DATE(date) = '2020-06-01'
                        
Results:
[False]
[2020-06-01 16:13:01,635] {__init__.py:1611} INFO - Marking task as FAILED.
[2020-06-01 16:13:01,647] {base_task_runner.py:101} INFO - Job 43: Subtask check_public_data_exists Traceback (most recent call last):
[2020-06-01 16:13:01,647] {base_task_runner.py:101} INFO - Job 43: Subtask check_public_data_exists   File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/bin/airflow", line 32, in <module>
[2020-06-01 16:13:01,647] {base_task_runner.py:101} INFO - Job 43: Subtask check_public_data_exists     args.func(args)
[2020-06-01 16:13:01,647] {base_task_runner.py:101} INFO - Job 43: Subtask check_public_data_exists   File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2020-06-01 16:13:01,647] {base_task_runner.py:101} INFO - Job 43: Subtask check_public_data_exists     return f(*args, **kwargs)
[2020-06-01 16:13:01,647] {base_task_runner.py:101} INFO - Job 43: Subtask check_public_data_exists   File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/bin/cli.py", line 523, in run
[2020-06-01 16:13:01,647] {base_task_runner.py:101} INFO - Job 43: Subtask check_public_data_exists     _run(args, dag, ti)
[2020-06-01 16:13:01,647] {base_task_runner.py:101} INFO - Job 43: Subtask check_public_data_exists   File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/bin/cli.py", line 442, in _run
[2020-06-01 16:13:01,648] {base_task_runner.py:101} INFO - Job 43: Subtask check_public_data_exists     pool=args.pool,
[2020-06-01 16:13:01,648] {base_task_runner.py:101} INFO - Job 43: Subtask check_public_data_exists   File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/utils/db.py", line 73, in wrapper
[2020-06-01 16:13:01,648] {base_task_runner.py:101} INFO - Job 43: Subtask check_public_data_exists     return func(*args, **kwargs)
[2020-06-01 16:13:01,648] {base_task_runner.py:101} INFO - Job 43: Subtask check_public_data_exists   File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/models/__init__.py", line 1441, in _run_raw_task
[2020-06-01 16:13:01,648] {base_task_runner.py:101} INFO - Job 43: Subtask check_public_data_exists     result = task_copy.execute(context=context)
[2020-06-01 16:13:01,648] {base_task_runner.py:101} INFO - Job 43: Subtask check_public_data_exists   File "/Users/rebecca.vickery/.local/share/virtualenvs/airflow_sandbox-x5mYwKUH/lib/python3.7/site-packages/airflow/operators/check_operator.py", line 87, in execute
[2020-06-01 16:13:01,648] {base_task_runner.py:101} INFO - Job 43: Subtask check_public_data_exists     raise AirflowException(exceptstr.format(q=self.sql, r=records))
[2020-06-01 16:13:01,648] {base_task_runner.py:101} INFO - Job 43: Subtask check_public_data_exists airflow.exceptions.AirflowException: Test failed.
[2020-06-01 16:13:01,648] {base_task_runner.py:101} INFO - Job 43: Subtask check_public_data_exists Query:
[2020-06-01 16:13:01,648] {base_task_runner.py:101} INFO - Job 43: Subtask check_public_data_exists 
[2020-06-01 16:13:01,648] {base_task_runner.py:101} INFO - Job 43: Subtask check_public_data_exists                             select count(*) > 0
[2020-06-01 16:13:01,648] {base_task_runner.py:101} INFO - Job 43: Subtask check_public_data_exists                             from bigquery-public-data.covid19_italy.data_by_region
[2020-06-01 16:13:01,648] {base_task_runner.py:101} INFO - Job 43: Subtask check_public_data_exists                             where DATE(date) = '2020-06-01'
[2020-06-01 16:13:01,648] {base_task_runner.py:101} INFO - Job 43: Subtask check_public_data_exists                         
[2020-06-01 16:13:01,648] {base_task_runner.py:101} INFO - Job 43: Subtask check_public_data_exists Results:
[2020-06-01 16:13:01,648] {base_task_runner.py:101} INFO - Job 43: Subtask check_public_data_exists [False]
[2020-06-01 16:13:03,072] {logging_mixin.py:95} INFO - [2020-06-01 16:13:03,072] {jobs.py:2562} INFO - Task exited with return code 1
